version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/home/node/app
    command: ["./wait-for-it.sh", "db:27017", "--", "npm", "start"]
    ports:
     - "${PORT}:${PORT}"  # Mapeia a porta do contêiner para a porta configurada em PORT no .env
    env_file:
      - .env  # Isso carrega as variáveis de ambiente do arquivo .env para o serviço

  db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
